language: ruby
rvm:
  - 2.6.0
before_install:
  - gem install bundler -v 1.17.3
bundler_args: --deployment
cache: bundler
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rspec
env:
  global:
    - secure: "P8+ZugrE8MxTcGQ+2X9FGq5aqjMyRH4HP/fU2q4AB8NYJOX0Sjr00qj3TfUVda/qMmwo8UoR2dNV3uxu+aBLP3b9+IRy5KXN/ajRjjQxpjbGCKBOvS/0Kc+zWmVvULw6Br0WB3Eam8tvXJAF3z/WmE+iB3jFa/JF2hUVTa3ASRLTJesn6KelXkLj+AnJTh3iBMG+fSpDrur3eupNjpNDajdA08gayky36qD0ZscQ1eHmsCG7P2aZouT9hAWwHUYCtjV+NQe99pc3JdLruhjwSWtTYslGbbo9g33KD+f20pp6655TN3JJLgaoa4d3UWA0BtfgoqO+GZmKwzzmztyZKRnRWc++M2o35i2LJwkSudZIch4LMCeGFrzOavtYOIL6SlRcgj26T57DgfK6X8+KupAJLbO/mDgdtu+K7KJ/WL9ST5joMle26Wn/OisVYriZ/6J4SGd2oRMD1cQ4z+y1AMhhTTagj7nV32zwVHLtPtTBDyovYrk52UIP4pRLwNomYx1inv3BzSw8eZAY6XpkC0EnJ52CdbFwEDDNANlPf8au3BPILTnD61nLG3zQg9+uHbysaSaMTDq0RGJZcCJbW/XXe+tqy75h1nrzT64WK8OngP/8Vy6+3aiRhDsFrD2By9cHeyeU+yrehSVcV7Mqoqbyq3myugwAjYBS+aF9gXM="
